export const recipe = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 3,
  gaps: "no",
  lowFodmap: false,
  aggregateLikes: 1,
  spoonacularScore: 72,
  healthScore: 27,
  creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
  license: "CC BY 3.0",
  sourceName: "Foodista",
  pricePerServing: 67.61,
  extendedIngredients: [
    {
      id: 2044,
      aisle: "Produce;Spices and Seasonings",
      image: "basil.jpg",
      consistency: "solid",
      name: "basil",
      nameClean: "fresh basil",
      original: "1 1/2 teaspoons Basil, crumbled",
      originalString: "1 1/2 teaspoons Basil, crumbled",
      originalName: "Basil, crumbled",
      amount: 1.5,
      unit: "teaspoons",
      meta: ["crumbled"],
      metaInformation: ["crumbled"],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 1002030,
      aisle: "Spices and Seasonings",
      image: "pepper.jpg",
      consistency: "solid",
      name: "black pepper",
      nameClean: "black pepper",
      original: "1/2 teaspoon black pepper",
      originalString: "1/2 teaspoon black pepper",
      originalName: "black pepper",
      amount: 0.5,
      unit: "teaspoon",
      meta: ["black"],
      metaInformation: ["black"],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 19334,
      aisle: "Baking",
      image: "light-brown-sugar.jpg",
      consistency: "solid",
      name: "brown sugar",
      nameClean: "golden brown sugar",
      original: "1 tablespoon brown sugar, packed",
      originalString: "1 tablespoon brown sugar, packed",
      originalName: "brown sugar, packed",
      amount: 1,
      unit: "tablespoon",
      meta: ["packed"],
      metaInformation: ["packed"],
      measures: {
        us: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 10011693,
      aisle: "Canned and Jarred",
      image: "tomatoes-canned.png",
      consistency: "solid",
      name: "canned tomatoes",
      nameClean: "canned tomatoes",
      original: "1 28 oz can whole tomatoes, undrained/crushed",
      originalString: "1 28 oz can whole tomatoes, undrained/crushed",
      originalName: "whole tomatoes, undrained/crushed",
      amount: 28,
      unit: "oz",
      meta: ["whole", "canned"],
      metaInformation: ["whole", "canned"],
      measures: {
        us: {
          amount: 28,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 793.787,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 11124,
      aisle: "Produce",
      image: "sliced-carrot.png",
      consistency: "solid",
      name: "carrot",
      nameClean: "carrot",
      original: "1 cup carrot, sliced",
      originalString: "1 cup carrot, sliced",
      originalName: "carrot, sliced",
      amount: 1,
      unit: "cup",
      meta: ["sliced"],
      metaInformation: ["sliced"],
      measures: {
        us: {
          amount: 1,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 236.588,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 11143,
      aisle: "Produce",
      image: "celery.jpg",
      consistency: "solid",
      name: "celery",
      nameClean: "celery",
      original: "1 cup celery, sliced",
      originalString: "1 cup celery, sliced",
      originalName: "celery, sliced",
      amount: 1,
      unit: "cup",
      meta: ["sliced"],
      metaInformation: ["sliced"],
      measures: {
        us: {
          amount: 1,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 236.588,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 6194,
      aisle: "Canned and Jarred",
      image: "chicken-broth.png",
      consistency: "liquid",
      name: "chicken broth",
      nameClean: "chicken broth",
      original: "3 chicken broth,",
      originalString: "3 chicken broth,",
      originalName: "chicken broth",
      amount: 3,
      unit: "",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 3,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 3,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 11215,
      aisle: "Produce",
      image: "garlic.png",
      consistency: "solid",
      name: "garlic",
      nameClean: "garlic",
      original: "1 Clove (large) garlic, minced",
      originalString: "1 Clove (large) garlic, minced",
      originalName: "(large) garlic, minced",
      amount: 1,
      unit: "Clove",
      meta: ["minced", "(large)"],
      metaInformation: ["minced", "(large)"],
      measures: {
        us: {
          amount: 1,
          unitShort: "Clove",
          unitLong: "Clove",
        },
        metric: {
          amount: 1,
          unitShort: "Clove",
          unitLong: "Clove",
        },
      },
    },
    {
      id: 11052,
      aisle: "Produce",
      image: "green-beans-or-string-beans.jpg",
      consistency: "solid",
      name: "green beans",
      nameClean: "green beans",
      original: "1 9 oz pkg green beans, frozen",
      originalString: "1 9 oz pkg green beans, frozen",
      originalName: "pkg green beans, frozen",
      amount: 9,
      unit: "oz",
      meta: ["frozen"],
      metaInformation: ["frozen"],
      measures: {
        us: {
          amount: 9,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 255.146,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 20499,
      aisle: "Pasta and Rice",
      image: "elbow.jpg",
      consistency: "solid",
      name: "macaroni",
      nameClean: "short pasta",
      original: "1 cup macaroni, uncooked",
      originalString: "1 cup macaroni, uncooked",
      originalName: "macaroni, uncooked",
      amount: 1,
      unit: "cup",
      meta: ["uncooked"],
      metaInformation: ["uncooked"],
      measures: {
        us: {
          amount: 1,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 236.588,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 2023,
      aisle: "Produce;Spices and Seasonings",
      image: "marjoram.jpg",
      consistency: "solid",
      name: "marjoram",
      nameClean: "marjoram",
      original: "1/2 teaspoon marjoram",
      originalString: "1/2 teaspoon marjoram",
      originalName: "marjoram",
      amount: 0.5,
      unit: "teaspoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 11282,
      aisle: "Produce",
      image: "brown-onion.png",
      consistency: "solid",
      name: "onion",
      nameClean: "onion",
      original: "1 medium Onion, chopped",
      originalString: "1 medium Onion, chopped",
      originalName: "Onion, chopped",
      amount: 1,
      unit: "medium",
      meta: ["chopped"],
      metaInformation: ["chopped"],
      measures: {
        us: {
          amount: 1,
          unitShort: "medium",
          unitLong: "medium",
        },
        metric: {
          amount: 1,
          unitShort: "medium",
          unitLong: "medium",
        },
      },
    },
    {
      id: 2027,
      aisle: "Produce;Spices and Seasonings",
      image: "oregano.jpg",
      consistency: "solid",
      name: "oregano",
      nameClean: "oregano",
      original: "1 1/2 teaspoons Oregano, crumbled",
      originalString: "1 1/2 teaspoons Oregano, crumbled",
      originalName: "Oregano, crumbled",
      amount: 1.5,
      unit: "teaspoons",
      meta: ["crumbled"],
      metaInformation: ["crumbled"],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 1033,
      aisle: "Cheese",
      image: "parmesan.jpg",
      consistency: "solid",
      name: "parmesan cheese",
      nameClean: "parmesan",
      original: "1 cup Grated Parmesan cheese",
      originalString: "1 cup Grated Parmesan cheese",
      originalName: "Grated Parmesan cheese",
      amount: 1,
      unit: "cup",
      meta: ["grated"],
      metaInformation: ["grated"],
      measures: {
        us: {
          amount: 1,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 236.588,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 2049,
      aisle: "Produce;Spices and Seasonings",
      image: "thyme.jpg",
      consistency: "solid",
      name: "thyme",
      nameClean: "thyme",
      original: "1/2 teaspoon thyme",
      originalString: "1/2 teaspoon thyme",
      originalName: "thyme",
      amount: 0.5,
      unit: "teaspoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 11887,
      aisle: "Pasta and Rice",
      image: "tomato-paste.jpg",
      consistency: "solid",
      name: "tomato paste",
      nameClean: "tomato paste",
      original: "1 6 oz can tomato paste",
      originalString: "1 6 oz can tomato paste",
      originalName: "tomato paste",
      amount: 6,
      unit: "oz",
      meta: ["canned"],
      metaInformation: ["canned"],
      measures: {
        us: {
          amount: 6,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 170.097,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 14412,
      aisle: "Beverages",
      image: "water.png",
      consistency: "liquid",
      name: "water",
      nameClean: "water",
      original: "1 1/2 quarts Boiling water",
      originalString: "1 1/2 quarts Boiling water",
      originalName: "Boiling water",
      amount: 1.5,
      unit: "quarts",
      meta: ["boiling"],
      metaInformation: ["boiling"],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "qts",
          unitLong: "quarts",
        },
        metric: {
          amount: 1.42,
          unitShort: "l",
          unitLong: "liters",
        },
      },
    },
  ],
  id: 654883,
  title: "Pasta Vegetable Soup",
  readyInMinutes: 45,
  servings: 10,
  sourceUrl: "http://www.foodista.com/recipe/FR8FKR4F/pasta-vegetable-soup",
  image: "https://spoonacular.com/recipeImages/654883-556x370.jpg",
  imageType: "jpg",
  summary:
    'Pasta Vegetable Soup might be just the soup you are searching for. For <b>64 cents per serving</b>, this recipe <b>covers 14%</b> of your daily requirements of vitamins and minerals. One serving contains <b>167 calories</b>, <b>10g of protein</b>, and <b>3g of fat</b>. It is perfect for <b>Autumn</b>. Only a few people made this recipe, and 1 would say it hit the spot. A mixture of onion, water, thyme, and a handful of other ingredients are all it takes to make this recipe so flavorful. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 78%</b>. This score is good. Try <a href="https://spoonacular.com/recipes/beef-and-pasta-vegetable-soup-411736">Beef and Pasta Vegetable Soup</a>, <a href="https://spoonacular.com/recipes/pantry-vegetable-and-pasta-soup-530939">Pantry Vegetable and Pasta Soup</a>, and <a href="https://spoonacular.com/recipes/easy-vegetable-soup-with-pasta-699450">Easy Vegetable Soup with Pasta</a> for similar recipes.',
  cuisines: [],
  dishTypes: ["soup"],
  diets: [],
  occasions: ["fall", "winter"],
  winePairing: {
    pairedWines: [],
    pairingText:
      "No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
    productMatches: [],
  },
  instructions:
    "<ol><li>In a large sauce pan, combine 4 cups water, onion, carrot, celery, brown sugar, basil, marjoram, oregano, thyme, pepper, garlic, chicken broth, tomatoes, beans, and tomato paste then bring to a boil. Cover, reduce heat, and simmer 45 minutes. Add remaining 2 cups water; bring to a boil. Stir in macaroni, and cook an additional 8 minutes. Ladle into soup bowls; top with Parmesan cheese.</li></ol>",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "In a large sauce pan, combine 4 cups water, onion, carrot, celery, brown sugar, basil, marjoram, oregano, thyme, pepper, garlic, chicken broth, tomatoes, beans, and tomato paste then bring to a boil. Cover, reduce heat, and simmer 45 minutes.",
          ingredients: [
            {
              id: 6194,
              name: "chicken broth",
              localizedName: "chicken broth",
              image: "chicken-broth.png",
            },
            {
              id: 11887,
              name: "tomato paste",
              localizedName: "tomato paste",
              image: "tomato-paste.jpg",
            },
            {
              id: 19334,
              name: "brown sugar",
              localizedName: "brown sugar",
              image: "dark-brown-sugar.png",
            },
            {
              id: 2023,
              name: "marjoram",
              localizedName: "marjoram",
              image: "marjoram.jpg",
            },
            {
              id: 11529,
              name: "tomato",
              localizedName: "tomato",
              image: "tomato.png",
            },
            {
              id: 2027,
              name: "oregano",
              localizedName: "oregano",
              image: "oregano.jpg",
            },
            {
              id: 11124,
              name: "carrot",
              localizedName: "carrot",
              image: "sliced-carrot.png",
            },
            {
              id: 11143,
              name: "celery",
              localizedName: "celery",
              image: "celery.jpg",
            },
            {
              id: 11215,
              name: "garlic",
              localizedName: "garlic",
              image: "garlic.png",
            },
            {
              id: 1002030,
              name: "pepper",
              localizedName: "pepper",
              image: "pepper.jpg",
            },
            {
              id: 2044,
              name: "basil",
              localizedName: "basil",
              image: "basil.jpg",
            },
            {
              id: 0,
              name: "beans",
              localizedName: "beans",
              image: "kidney-beans.jpg",
            },
            {
              id: 11282,
              name: "onion",
              localizedName: "onion",
              image: "brown-onion.png",
            },
            {
              id: 0,
              name: "sauce",
              localizedName: "sauce",
              image: "",
            },
            {
              id: 2049,
              name: "thyme",
              localizedName: "thyme",
              image: "thyme.jpg",
            },
            {
              id: 14412,
              name: "water",
              localizedName: "water",
              image: "water.png",
            },
          ],
          equipment: [
            {
              id: 404669,
              name: "sauce pan",
              localizedName: "sauce pan",
              image: "sauce-pan.jpg",
            },
          ],
          length: {
            number: 45,
            unit: "minutes",
          },
        },
        {
          number: 2,
          step: "Add remaining 2 cups water; bring to a boil. Stir in macaroni, and cook an additional 8 minutes. Ladle into soup bowls; top with Parmesan cheese.",
          ingredients: [
            {
              id: 1033,
              name: "parmesan",
              localizedName: "parmesan",
              image: "parmesan.jpg",
            },
            {
              id: 20499,
              name: "macaroni",
              localizedName: "macaroni",
              image: "macaroni.png",
            },
            {
              id: 14412,
              name: "water",
              localizedName: "water",
              image: "water.png",
            },
            {
              id: 0,
              name: "soup",
              localizedName: "soup",
              image: "",
            },
          ],
          equipment: [
            {
              id: 404783,
              name: "bowl",
              localizedName: "bowl",
              image: "bowl.jpg",
            },
            {
              id: 404630,
              name: "ladle",
              localizedName: "ladle",
              image: "ladle.jpg",
            },
          ],
          length: {
            number: 8,
            unit: "minutes",
          },
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl: "https://spoonacular.com/pasta-vegetable-soup-654883",
};
